Repository wecode-bootcamp-korea/fullstack3-1st-wetown-frontend, pull requests merged in 2022-01, with the labels that each got.

#11 SignUp UI- 1차
  public/data/mockCategory.json
  public/index.html
  src/components/CircleButton/CircleButton.js
  src/components/CircleButton/CircleButton.scss
  src/pages/SignUp/Policy.js
  src/pages/SignUp/Policy.scss
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
Labels: ⚙️ 기능구현완료

#15 [회원가입] SignUp UI 2차 - 유효성 검사 1차
  src/pages/SignUp/SignUp.js
Labels: 🐎 진행중

#10 [추가] 헤더 최상단 로그인, 회원가입, 언어 선택 드롭 다운 구현
  .gitignore
  package-lock.json
  public/data/imgData.json
  public/icons/main/back_arrow.png
  public/icons/main/bookmarks.svg
  public/icons/main/left_arrow.svg
  public/icons/main/mainIcon.svg
  public/icons/main/person.svg
  public/icons/main/right_arrow.svg
  public/icons/main/search.svg
  public/icons/main/shopping_cart.svg
  public/images/mainSlider/bird.jpg
  public/images/mainSlider/cat.jpg
  public/images/mainSlider/hamster.jpg
  public/images/mainSlider/puppy_smile.jpg
  public/images/mainSlider/turtle.jpg
  public/images/puppy.jpg
  src/components/HeaderNav/HeaderNav.js
  src/components/HeaderNav/HeaderNav.scss
  src/components/Sliders/MainSlider/BtnSlider.js
  src/components/Sliders/MainSlider/BtnSlider.scss
  src/components/Sliders/MainSlider/MainSlider.js
  src/components/Sliders/MainSlider/MainSlider.scss
  src/components/Sliders/MainSlider/sliderData.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/PetProductBox.js
  src/pages/Main/PetProductBox.scss
Labels: ⚙️ 기능구현완료

#18 [회원가입/로그인] - axios로 통신 변경, 유효성 검사 및 로그인 redirect, 약관동의 체크리스트
  .gitignore
  package-lock.json
  package.json
  src/components/HeaderNav/HeaderNav.js
  src/pages/SignIn/SignIn.js
  src/pages/SignUp/Policy.js
  src/pages/SignUp/Policy.scss
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
Labels: 🚨 도움요청

#17 Feature/Detail Page 1차
  public/images/ad.png
  public/images/cart.png
  public/images/change.png
  public/images/close.png
  public/images/corona.png
  public/images/delivery.png
  public/images/info.png
  public/images/new.png
  public/images/open.png
  public/images/quality.png
  public/images/shareIcon.png
  public/images/tobottom.png
  public/images/totop.png
  src/Router.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/compo/slider.js
  src/pages/ProductDetail/images/left.png
  src/pages/ProductDetail/images/right.png
  src/pages/SignUp/SignUp.scss
Labels: ⚙️ 기능구현완료

#25 Feature/footer
  public/images/apple.svg
  public/images/arrow-down.svg
  public/images/external-link-alt-solid.svg
  public/images/facebook.svg
  public/images/instagram.svg
  public/images/twitter.svg
  public/images/youtube.svg
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/pages/ProductList/ProductList.js
Labels: ⚙️ 기능구현완료

#47 [공통] 페이지 이동시 스크롤 위로 시작
  src/Router.js
  src/components/CircleButton/CircleButton.scss
  src/components/ScrollToTop.js
  src/pages/SignIn/SignIn.js
  src/pages/SignIn/SignIn.scss
  src/pages/SignUp/Policy.scss
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
Labels: 🐎 진행중

#51 [추가] pet for u 사진 늘리고 동적으로 바꾸기
  src/components/HeaderNav/HeaderNav.js
  src/components/HeaderNav/HeaderNav.scss
  src/components/Sliders/MainSlider/MainSlider.js
  src/components/Sliders/MainSlider/MainSlider.scss
  src/pages/Main/PetProductBox.js
  src/pages/Main/PetProductBox.scss
Labels: ⚙️ 기능구현완료

#55 [메인슬라이더] 이미지 옆에 상세 문구 추가
  src/components/Sliders/MainSlider/BtnSlider.js
  src/components/Sliders/MainSlider/BtnSlider.scss
  src/components/Sliders/MainSlider/MainSlider.js
  src/components/Sliders/MainSlider/MainSlider.scss
  src/components/Sliders/MainSlider/sliderData.js
Labels: ⚙️ 기능구현완료
